/* Generated by configure */
#include <windows.h>
#include <ntddmodm.h>
int main(int argc, char **argv)
{
    (void)argc; (void)argv;
    /* BEGIN TEST: */
    GUID guid = GUID_DEVINTERFACE_MODEM;
    /* END TEST */
    return 0;
}
