/* Generated by configure */
#include <flite/flite.h>
static int fliteAudioCb(const cst_wave *, int, int, int, cst_audio_streaming_info *)
{ return CST_AUDIO_STREAM_STOP; }
int main(int argc, char **argv)
{
    (void)argc; (void)argv;
    /* BEGIN TEST: */
    cst_audio_streaming_info *asi = new_audio_streaming_info();
    asi->asc = fliteAudioCb; // This fails for old Flite
    new_audio_streaming_info();
    /* END TEST */
    return 0;
}
