/* Generated by configure */
int main(int argc, char **argv)
{
    (void)argc; (void)argv;
    /* BEGIN TEST: */
    #if !defined(__CET__)
    #  error Intel CET not available
    #endif
    /* END TEST */
    return 0;
}
