/* Generated by configure */
#include <libxml/xmlversion.h>
#if !defined(LIBXML_ICU_ENABLED)
#error libxml icu not enabled
#endif
int main(int argc, char **argv)
{
    (void)argc; (void)argv;
    /* BEGIN TEST: */
    /* END TEST */
    return 0;
}
