/* Generated by configure */
#include <limits>
int main(int argc, char **argv)
{
    (void)argc; (void)argv;
    /* BEGIN TEST: */
    using B = std::numeric_limits<double>;
    static_assert(B::has_signaling_NaN, "System lacks signaling NaN");
    /* END TEST */
    return 0;
}
