/* Generated by configure */
#include <libspeechd.h>
int main(int argc, char **argv)
{
    (void)argc; (void)argv;
    /* BEGIN TEST: */
    spd_close(spd_open("QtConfigTest", "main", 0, SPD_MODE_THREADED));
    /* END TEST */
    return 0;
}
