/* Generated by configure */
#include <zstd.h>
int main(int argc, char **argv)
{
    (void)argc; (void)argv;
    /* BEGIN TEST: */
    (void) ZSTD_compress(NULL, 0, NULL, 0, 1);
    unsigned long long n = ZSTD_getFrameContentSize(NULL, 0);
    (void) ZSTD_decompress(NULL, 0, NULL, n);
    /* END TEST */
    return 0;
}
