/* Generated by configure */
#if defined(__APPLE__) && (defined(__GNUC__) || defined(__xlC__) || defined(__xlc__))
#  include <TargetConditionals.h>
#  if defined(TARGET_OS_MAC) && TARGET_OS_MAC
#    include <GSS/GSS.h>
#  endif
#else
#  include <gssapi/gssapi.h>
#endif
int main(int argc, char **argv)
{
    (void)argc; (void)argv;
    /* BEGIN TEST: */
    gss_ctx_id_t ctx;
    gss_context_time(nullptr, ctx, nullptr);
    /* END TEST */
    return 0;
}
